(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.flags = function() {
	this.initialize(img.flags);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,209,131);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.rect1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Eg54ACWIAAkrMBzxAAAIAAErg");
	this.shape.setTransform(370.5,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.rect1, new cjs.Rectangle(0,-15,741,30), null);


(lib.point2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#e60e35").s().p("AiQCRQg8g8AAhVQAAhUA8g8QA7g8BVAAQBVAAA8A8QA8A8AABUQAABVg8A8Qg8A8hVAAQhVAAg7g8g");

	this.shape_1 = new cjs.Shape();
	
	this.shape_1.graphics.f("#eb4261").s().p("AjTDUIAAAAQhYhYAAh8QAAh7BYhYIAAAAQBXhYB8AAQB8AABYBYQBYBYAAB7QAAB8hYBYQhYBYh8AAQh8AAhXhYgAiQiQQg8A8AABUQAABVA8A8QA7A8BVAAQBVAAA8g8QA8g8AAhVQAAhUg8g8Qg8g8hVAAQhVAAg7A8g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.point2, new cjs.Rectangle(-30,-30,60,60), null);


(lib.point = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#e60e35").s().p("AiMCNQg7g6AAhTQAAhSA7g6QA6g7BSAAQBTAAA6A7QA7A6AABSQAABTg7A6Qg6A7hTAAQhSAAg6g7g");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFF").s().p("AjTDUIAAAAQhYhYAAh8QAAh7BYhYIAAAAQBXhYB8AAQB8AABYBYQBYBYAAB7QAAB8hYBYQhYBYh8AAQh8AAhXhYgAiMiMQg7A6AABSQAABTA7A6QA6A7BSAAQBTAAA6g7QA7g6AAhTQAAhSg7g6Qg6g7hTAAQhSAAg6A7g");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.point, new cjs.Rectangle(-30,-30,60,60), null);


(lib.mask = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#eb4261").s().p("Eg51AlgQm3AAk2k3Qk3k2AAm3IAAlUQAAm4E3k2QE2k1G3AAMBzrAAAQGFAAETkTQEUkUAAmFIAAlUQAAmGkUkTQkTkTmFAAMhjNAAAIAAh4MBjNAAAQG3AAE2E2QE3E2AAG4IAAFUQAAG3k3E2Qk2E2m3AAMhzrAAAQmFAAkTETQkUETAAGGIAAFUQAAGFEUEUQETETGFAAMBjnAAAQAZAAASARQARASAAAZQAAAZgRASQgSARgZAAg");
	this.shape.setTransform(476.2,240);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,952.4,480);


(lib.half_circle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMjMjYt2AArPrPAAt2IZFAAg");
	this.shape.setTransform(75,75,0.934,0.935,-90);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.half_circle, new cjs.Rectangle(0,0,150,150), null);


(lib.Pin = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF0000").s().p("AhSBTQgJgKgIgLIgDgGQgOgagBgeQABgwAigjQAjghAvgBQAxABAiAhQAiAjAAAwQAAAigQAbIgCACQgGAKgKAKQgiAjgxgBQgvABgjgjg");
	this.shape.setTransform(0.1,-9.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFBFD").s().p("AjDAKIgJgNQgbgxAAg8QAAhhBEhFQBEhDBfAAQBgAABFBDQBDBFAABhQABBDgiA0IjHFTg");
	this.shape_1.setTransform(0,2.4);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// Layer 4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0068B1").s().p("AkOAPIgLgTIgBAAQglhFAAhSQAAiFBdheIAAAAQBfheCDAAQCFAABeBeQBdBeAACFQAABdguBJIAAgCIkSHUg");
	this.shape_2.setTransform(0,6.7);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1));

}).prototype = getMCSymbolPrototype(lib.Pin, new cjs.Rectangle(-32,-41,64,95.4), null);


(lib.flags_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.flags();
	this.instance.parent = this;
	this.instance.setTransform(-104.5,-65.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.flags_1, new cjs.Rectangle(-104.5,-65.5,209,131), null);


(lib.fotootchet = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#ff9797").s().p("AgVA2QgJgDgHgGQgGgHgEgLQgDgLAAgQQAAgbAMgPQAMgOAaAAQAaAAAMANQANAPAAAcQAAAQgEALQgDALgHAHQgHAGgJADQgKADgLAAQgLAAgKgDgAgPgoQgHADgEAFQgDAGgCAJQgCAHAAAKQAAAKACAIQACAJAEAGQADAFAHADQAGACAJABQAJgBAHgCQAGgDAEgFQAEgGACgIQABgIAAgKQAAgKgCgJQgBgIgEgGQgEgGgHgCQgGgDgJAAQgJAAgGADg");
	this.shape.setTransform(78.5,-1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#ff9797").s().p("AgfA3IgCAAIgBgCIAAhpIABgCIACAAIA+AAQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAIgxAAIAAAhIApAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgpAAIAAAmIAyAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_1.setTransform(68,-1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#ff9797").s().p("AAtBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgZIhUAAIAAAZQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAIgCgBIAAgBIgCgkQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAIAIgRIAGgQQACgLAAgNIABgZIAAgMQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBAAAIACABIABACIAABeIAOAAIACAAIAAACIgBAkQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgLgqIgBAVIgDAUIgFAPQgCAIgFAHIA1AAIAAhTIglAAg");
	this.shape_2.setTransform(56.5,-0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(44.5,-1.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#ff9797").s().p("AglA3QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhpQgBgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAnAAQARAAAJAGQAJAGAAAPQAAAJgEAGQgFAGgJAEIAAAAQALACAFAHQAHAHgBALQAAAIgCAGQgEAGgEADQgGAEgHACQgHACgHgBgAgXArIAYAAIAJgBQAEgBADgCQADgCACgEQABgDAAgGQAAgFgBgEIgGgGIgGgDIgJgCIgYAAgAgXgHIAXAAIAHgBQAEgBACgBQADgCABgEQACgEAAgFIgBgIQgBgEgDgBQgDgCgDgBIgIAAIgXAAg");
	this.shape_4.setTransform(33.3,-1.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#ff9797").s().p("AgfBHIgDAAIAAgCIAAhpIAAgCIADAAIA/AAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgyAAIAAAgIAqAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAJQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgqAAIAAAmIAzAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAAJg9QAAgFADgDQACgCAEAAQAFABADACQACACAAAFQAAAJgKAAQgJAAAAgJgAgcg9QABgFACgDQACgCAFAAQAFABADACQACACAAAFQAAAJgKAAQgKAAAAgJg");
	this.shape_5.setTransform(18.3,-3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#ff9797").s().p("AgVA2QgJgDgHgGQgGgHgEgLQgDgLAAgQQAAgbAMgPQAMgOAaAAQAaAAAMANQANAPAAAcQAAAQgEALQgDALgHAHQgHAGgJADQgKADgLAAQgLAAgKgDgAgPgoQgHADgEAFQgDAGgCAJQgCAHAAAKQAAAKACAIQACAJAEAGQADAFAHADQAGACAJABQAJgBAHgCQAGgDAEgFQAEgGACgIQABgIAAgKQAAgKgCgJQgBgIgEgGQgEgGgHgCQgGgDgJAAQgJAAgGADg");
	this.shape_6.setTransform(7,-1.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#ff9797").s().p("AglA3QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAmAAQASAAAJAGQAJAGAAAPQAAAJgEAGQgEAGgKAEIAAAAQALACAFAHQAHAHAAALQAAAIgDAGQgEAGgEADQgGAEgHACQgHACgHgBgAgXArIAXAAIAJgBQAFgBADgCQADgCACgEQABgDAAgGQAAgFgBgEIgGgGIgHgDIgJgCIgXAAgAgXgHIAXAAIAHgBQAEgBADgBQACgCABgEQACgEAAgFIgBgIQgBgEgDgBQgDgCgDgBIgIAAIgXAAg");
	this.shape_7.setTransform(-4.1,-1.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#ff9797").s().p("AgdArQgMgOAAgdQAAgcAMgPQANgNAZAAIAJAAIAJABIAHACQADAAADACQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIgEAJIgBABIgCAAIgGgDIgFgCIgHgBIgIAAQgJAAgHADQgGAEgEAFQgEAHgBAHQgCAIAAAIQAAAKACAIQACAIAEAGQAEAGAGADQAGAEAJAAIAJgBIAHgBIAGgCIAFgCIACAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIADAJQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABIgGACIgHABIgJACIgJAAQgaAAgNgOg");
	this.shape_8.setTransform(-14.5,-1.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(-30.9,-1.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#ff9797").s().p("AAtBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgZIhUAAIAAAZQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAIgCgBIAAgBIgCgkQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAIAIgRIAGgQQACgLAAgNIABgZIAAgMQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBAAAIACABIAAACIAABeIAPAAIACAAIAAACIgBAkQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgLgqIgBAVIgDAUIgFAPQgCAIgFAHIA1AAIAAhTIglAAg");
	this.shape_10.setTransform(-43.4,-0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#ff9797").s().p("AAfBHQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhFIAAgKIABgKIgBAAIgEAJIgFAJIgsBHIgBACIgCAAIgPAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhpIAAgCIACgBIAMAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAABBIAAALIgBAKIABAAIAEgJIAGgJIAqhFQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABpQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAgAgSg0QgEgCgBgFQgCgEAAgFQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAGACADIAEACIAFAAIAGAAIAEgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBIABgFIABgBIACAAIAIAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgBAJQgCAEgEADQgGAFgNAAQgMAAgGgFg");
	this.shape_11.setTransform(-55.4,-3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#ff9797").s().p("AglA4IgNgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAqhpQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAPAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIApBpQAAAAAAABQABAAgBAAQAAABAAAAQAAAAgBAAIgNACQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgLgdIgvAAIgLAdQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgBAAgAgCghIgDAJIgOAkIAnAAIgOgkIgDgJIgDgKIAAAAIgCAKg");
	this.shape_12.setTransform(-67,-1.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#ff9797").s().p("AAeA3QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgwIg2AAIAAAwIgBACIgCAAIgLAAIgCAAIgBgCIAAhpIABgCIACAAIALAAIACAAIABACIAAAsIA2AAIAAgsIAAgCIACAAIALAAIACAAIABACIAABpQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_13.setTransform(-78.5,-1.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#ff9797").s().p("As9AFIAAgJIZ7AAIAAAJg");
	this.shape_14.setTransform(0,6.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#ff9797").s().p("AgVA2QgJgDgHgGQgGgHgEgLQgDgLAAgQQAAgbAMgPQAMgOAaAAQAaAAAMANQANAPAAAcQAAAQgEALQgDALgHAHQgHAGgJADQgKADgLAAQgLAAgKgDgAgPgoQgHADgEAFQgDAGgCAJQgCAHAAAKQAAAKACAIQACAJAEAGQADAFAHADQAGACAJABQAJgBAHgCQAGgDAEgFQAEgGACgIQABgIAAgKQAAgKgCgJQgBgIgEgGQgEgGgHgCQgGgDgJAAQgJAAgGADg");
	this.shape_15.setTransform(78.5,-1.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#ff9797").s().p("AgfA3IgCAAIgBgCIAAhpIABgCIACAAIA+AAQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAIgxAAIAAAhIApAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgpAAIAAAmIAyAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_16.setTransform(68,-1.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#ff9797").s().p("AAtBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgZIhUAAIAAAZQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAIgCgBIAAgBIgCgkQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAIAIgRIAGgQQACgLAAgNIABgZIAAgMQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBAAAIACABIABACIAABeIAOAAIACAAIAAACIgBAkQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgLgqIgBAVIgDAUIgFAPQgCAIgFAHIA1AAIAAhTIglAAg");
	this.shape_17.setTransform(56.5,-0.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQABAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_18.setTransform(44.5,-1.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#ff9797").s().p("AglA3QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhpQgBgBABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAnAAQARAAAJAGQAJAGAAAPQAAAJgEAGQgFAGgJAEIAAAAQALACAFAHQAHAHgBALQAAAIgCAGQgEAGgEADQgGAEgHACQgHACgHgBgAgXArIAYAAIAJgBQAEgBADgCQADgCACgEQABgDAAgGQAAgFgBgEIgGgGIgGgDIgJgCIgYAAgAgXgHIAXAAIAHgBQAEgBACgBQADgCABgEQACgEAAgFIgBgIQgBgEgDgBQgDgCgDgBIgIAAIgXAAg");
	this.shape_19.setTransform(33.3,-1.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#ff9797").s().p("AgfBHIgDAAIAAgCIAAhpIAAgCIADAAIA/AAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgyAAIAAAgIAqAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAJQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgqAAIAAAmIAzAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAgAAJg9QAAgFADgDQACgCAEAAQAFABADACQACACAAAFQAAAJgKAAQgJAAAAgJgAgcg9QABgFACgDQACgCAFAAQAFABADACQACACAAAFQAAAJgKAAQgKAAAAgJg");
	this.shape_20.setTransform(18.3,-3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#ff9797").s().p("AgVA2QgJgDgHgGQgGgHgEgLQgDgLAAgQQAAgbAMgPQAMgOAaAAQAaAAAMANQANAPAAAcQAAAQgEALQgDALgHAHQgHAGgJADQgKADgLAAQgLAAgKgDgAgPgoQgHADgEAFQgDAGgCAJQgCAHAAAKQAAAKACAIQACAJAEAGQADAFAHADQAGACAJABQAJgBAHgCQAGgDAEgFQAEgGACgIQABgIAAgKQAAgKgCgJQgBgIgEgGQgEgGgHgCQgGgDgJAAQgJAAgGADg");
	this.shape_21.setTransform(7,-1.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#ff9797").s().p("AglA3QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhpQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAmAAQASAAAJAGQAJAGAAAPQAAAJgEAGQgEAGgKAEIAAAAQALACAFAHQAHAHAAALQAAAIgDAGQgEAGgEADQgGAEgHACQgHACgHgBgAgXArIAXAAIAJgBQAFgBADgCQADgCACgEQABgDAAgGQAAgFgBgEIgGgGIgHgDIgJgCIgXAAgAgXgHIAXAAIAHgBQAEgBADgBQACgCABgEQACgEAAgFIgBgIQgBgEgDgBQgDgCgDgBIgIAAIgXAAg");
	this.shape_22.setTransform(-4.1,-1.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#ff9797").s().p("AgdArQgMgOAAgdQAAgcAMgPQANgNAZAAIAJAAIAJABIAHACQADAAADACQAAABABAAQAAAAAAABQAAAAAAABQABAAAAABIgEAJIgBABIgCAAIgGgDIgFgCIgHgBIgIAAQgJAAgHADQgGAEgEAFQgEAHgBAHQgCAIAAAIQAAAKACAIQACAIAEAGQAEAGAGADQAGAEAJAAIAJgBIAHgBIAGgCIAFgCIACAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIADAJQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABIgGACIgHABIgJACIgJAAQgaAAgNgOg");
	this.shape_23.setTransform(-14.5,-1.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_24.setTransform(-30.9,-1.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#ff9797").s().p("AAtBFQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAgZIhUAAIAAAZQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAIgCgBIAAgBIgCgkQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAMAAIAIgRIAGgQQACgLAAgNIABgZIAAgMQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBAAAIACABIAAACIAABeIAPAAIACAAIAAACIgBAkQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgLgqIgBAVIgDAUIgFAPQgCAIgFAHIA1AAIAAhTIglAAg");
	this.shape_25.setTransform(-43.4,-0.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#ff9797").s().p("AAfBHQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhFIAAgKIABgKIgBAAIgEAJIgFAJIgsBHIgBACIgCAAIgPAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhpIAAgCIACgBIAMAAQAAAAABAAQAAABAAAAQAAAAABABQAAAAAAABIAABBIAAALIgBAKIABAAIAEgJIAGgJIAqhFQABgBAAAAQAAAAABAAQAAgBAAAAQABAAAAAAIAQAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABpQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAgAgSg0QgEgCgBgFQgCgEAAgFQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAJAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQABAGACADIAEACIAFAAIAGAAIAEgCQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBIABgFIABgBIACAAIAIAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgBAJQgCAEgEADQgGAFgNAAQgMAAgGgFg");
	this.shape_26.setTransform(-55.4,-3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#ff9797").s().p("AglA4IgNgCQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAIAqhpQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAPAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAABIApBpQAAAAAAABQABAAgBAAQAAABAAAAQAAAAgBAAIgNACQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgLgdIgvAAIgLAdQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgBAAgAgCghIgDAJIgOAkIAnAAIgOgkIgDgJIgDgKIAAAAIgCAKg");
	this.shape_27.setTransform(-67,-1.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#ff9797").s().p("AAeA3QgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgwIg2AAIAAAwIgBACIgCAAIgLAAIgCAAIgBgCIAAhpIABgCIACAAIALAAIACAAIABACIAAAsIA2AAIAAgsIAAgCIACAAIALAAIACAAIABACIAABpQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_28.setTransform(-78.5,-1.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#ff9797").s().p("As9AFIAAgJIZ7AAIAAAJg");
	this.shape_29.setTransform(0,6.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#ff9797").s().p("AtUBkIAAjHIapAAIAADHg");
	this.shape_30.setTransform(0.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15}]},1).to({state:[{t:this.shape_30}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.5,-10,195.1,20.1);


(lib._continue = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgSBMQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAhuIgtAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAggQAAgBAAgBQAAAAABgBQAAAAAAAAQABAAABAAICFAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAAAgQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgtAAIAABuQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAg");
	this.shape.setTransform(46.2,10.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag2BMQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAiRQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAAAgBABQgBAAAAAAIhEAAIAAAWIAzAAQABAAABAAQABAAAAABQABAAAAABQAAAAAAABIAAAcQAAABAAAAQAAABgBAAQAAAAgBABQgBAAgBAAIgzAAIAAAZIBDAAQABAAABAAQAAABABAAQAAAAAAABQAAABAAAAIAAAdQAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(32.2,10.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgiBPIgKgCIgDgBIAAgDIAAgYQAAgFAEABIAJABIAIABQAPAAACgNQgHAAgFgCQgFgDgDgDQgEgEgDgEIgFgKIgghNQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIApgFQAAgBABAAQAAAAAAAAQABABAAAAQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAUA7IAEAMIACANIABAAIAEgOIADgMIAUg6QAAgBAAAAQABgBAAAAQAAAAABAAQABgBAAABIApAFQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgoBrQgEAMgGAJQgFAIgHAFQgHAGgIABQgIACgKAAIgNgBg");
	this.shape_2.setTransform(17.4,10.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA3BeQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAggIhoAAIAAAgQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAIgeAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIgFhAQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIATAAQAGgJADgJQAEgJADgMIAEgbQABgPAAgTIAAgOQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIBtAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAByIAZAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIgFBBQAAAAAAABQgBAAAAAAQAAAAgBABQAAAAgBAAgAgLguIgBATIgEAUIgFAQIgHAPIAyAAIAAhRIghAAg");
	this.shape_3.setTransform(0.5,12.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag2BMQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAiRQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAAAgBABQgBAAgBAAIhDAAIAAAWIA0AAQAAAAABAAQABAAAAABQABAAAAABQAAAAAAABIAAAcQAAABAAAAQAAABgBAAQAAAAgBABQgBAAAAAAIg0AAIAAAZIBDAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAAdQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(-15.4,10.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag/BOIgCgBIgJggQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIANgEQAFgBAEgFQAFgFACgMIABgPIAAgUIAAg2QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIBuAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAACRQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgmAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhwIggAAIAAANIAAAYQgBAMgCALIgCANIgDALIgEAKIgHAJQgJAJgKADQgLADgJAAIgEAAg");
	this.shape_5.setTransform(-31.8,11);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUBLQgPgEgJgKQgKgKgEgPQgFgPAAgVQAAgUAEgOQAFgQAJgJQAJgKAOgFQAOgFATAAIAPABIAOABIAKACIALAEQABAAAAAAQABAAAAABQAAABAAAAQAAABAAABIgIAgIgBABIgCAAIgIgDIgIgBIgKgCIgOgBQgJAAgEACQgGACgDAEQgDAFgBAIIgBATQAAAMACAIQABAJADAFQADAFAGACQAEACAIAAIANgBIAKgBIAEgBIAEgBIAFgBIAEgCQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAIAgQABAAAAABQAAAAgBABQAAAAAAABQgBAAAAAAIgEACIgFABIgHACIgHABIgNABIgMABQgTAAgPgFg");
	this.shape_6.setTransform(-46.2,10.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag2BMQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAiRQAAgBAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAAAgBABQgBAAgBAAIhDAAIAAAWIA0AAQAAAAABAAQABAAAAABQABAAAAABQAAAAAAABIAAAcQAAABAAAAQAAABgBAAQAAAAgBABQgBAAAAAAIg0AAIAAAZIBDAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAAdQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_7.setTransform(87.2,-15.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAhBMQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAhAIAAgPIABgOIgBAAIgGAMIgIARIgjBAIgBABIgCABIgvAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAiSQAAgBAAgBQAAAAABAAQAAgBABAAQAAAAABAAIAmAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAAA6IAAAJIgBAIIAAAJIAAAGIABAAIAEgIIAEgIIAEgGIAEgIIAfg8IACgBIADgBIAvAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAACTQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAg");
	this.shape_8.setTransform(71,-15.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAdBMQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAg5IgzAAIAAA5QAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgmAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAiRQAAgBAAgBQABAAAAAAQAAgBABAAQABAAAAAAIAmAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAA1IAzAAIAAg1QAAgBAAgBQAAAAAAAAQABgBAAAAQABAAABAAIAmAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABIAACRQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_9.setTransform(53.6,-15.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2BMQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAiRQAAgBAAgBQAAAAABAAQAAgBABAAQAAAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAdQAAABAAAAQAAABgBAAQAAAAgBABQgBAAAAAAIhEAAIAAAWIA0AAQAAAAABAAQABAAAAABQABAAAAABQAAAAAAABIAAAcQAAABAAAAQAAABgBAAQAAAAgBABQgBAAAAAAIg0AAIAAAZIBDAAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAAAdQAAABgBABQAAAAAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(38.3,-15.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("ABGBMIgTgpIgGgKIgFgFQgDgCgDgBIgKAAIgCAAIAAA6QAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAIglAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIAAg6IgCAAIgKAAQgEABgCACIgGAFIgEAKIgUApQAAABAAABQgBAAAAAAQgBAAgBABQAAAAgBgBIgqgHQAAAAgBgBQAAAAAAgBQgBAAABgBQAAAAAAgBIAQggIAIgNIAHgLIAJgJIAIgGIAAAAQgEgDgEgEQgEgFgCgFIgFgLIgEgHQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAIgFgBIgGAAIgDAAQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBABAAIACgeQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAFgBIARABQAHABAEADQAFADAEAFIAIAMIAJAUIAEAHIAGAEQADACADAAIAHAAIADAAIAAgzQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAlAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA0IADAAIAHAAQADAAADgCIAFgEIAFgHIAKgUIAHgMQADgFAFgDQAGgDAHgBIAQgBIAEABIACADIACAeIAAADIgEAAIgFAAIgFABQgBAAAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAIgEAHIgFALQgCAFgEAFQgEAEgEADIAAAAIAJAGIAIAJIAIALIAGANIARAgQAAABAAAAQABABgBAAQAAABAAAAQgBABAAAAIgqAHIgBABQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAgBg");
	this.shape_11.setTransform(19.1,-15.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ag/BNIgCgBIgJgeQAAgBAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIANgEQAFgCAEgEQAFgFACgMIABgPIAAgVIAAg1QAAgBABAAQAAgBAAAAQABgBAAAAQABAAABAAIBuAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAACSQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgmAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhxIggAAIAAAOIAAAXQgBAMgCAMIgCAMIgDAMIgEALIgHAJQgJAIgKADQgLADgJAAIgEgBg");
	this.shape_12.setTransform(-1.8,-15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgiBLQgOgEgJgKQgKgKgFgQQgEgPAAgVQAAgTAEgOQAFgPAIgKQAKgKAOgFQAPgFAUAAQAUAAAPAEQAOAEAKAKQAJAJAEAPQAFAPAAAVQAAAVgFAPQgEAQgKAKQgKAKgOAEQgPAFgTAAQgTAAgPgFgAgOgpQgFACgDAFQgDAEgCAJQgBAIAAANQAAAOABAJQACAIADAFQADAEAFACQAGABAIAAQAJAAAGgBQAFgCAEgFQACgEABgJQACgJAAgNQAAgOgCgIQgBgIgCgFQgEgEgFgCQgGgBgJAAQgIAAgGABg");
	this.shape_13.setTransform(-17.9,-15.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AA3BeQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAggIhoAAIAAAgQAAABAAAAQgBABAAAAQAAAAgBABQgBAAAAAAIgeAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIgFhAQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIATAAQAGgJADgJQAEgJADgMIAEgbQABgPAAgTIAAgOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIBtAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAByIAZAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIgFBBQAAAAAAABQgBAAAAAAQAAABgBAAQAAAAgBAAgAgLguIgBATIgEAUIgFAQIgHAPIAyAAIAAhRIghAAg");
	this.shape_14.setTransform(-35.8,-13.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgiBLQgOgEgJgKQgKgKgFgQQgEgPAAgVQAAgTAEgOQAEgPAKgKQAJgKAOgFQAPgFAUAAQATAAAPAEQAPAEAKAKQAJAJAEAPQAFAPAAAVQAAAVgFAPQgEAQgKAKQgJAKgPAEQgPAFgTAAQgTAAgPgFgAgNgpQgGACgDAFQgEAEgBAJQgBAIAAANQAAAOABAJQABAIAEAFQADAEAGACQAFABAIAAQAJAAAGgBQAFgCAEgFQACgEABgJQACgJAAgNQAAgOgCgIQgBgIgCgFQgEgEgFgCQgGgBgJAAQgIAAgFABg");
	this.shape_15.setTransform(-53.3,-15.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("Ag/BMQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBIAAiRQAAgBAAgBQABAAAAAAQAAgBABAAQABAAAAAAIBMAAQALAAAKADQAKADAHAGQAIAFAEAKQAEAJAAANQAAANgFAKQgEAIgIAHQgIAGgLADQgKADgNAAIgeAAIAAAxQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAgAgWgIIAeAAQAIAAADgEQADgEAAgKQAAgJgDgEQgDgDgHAAIgfAAg");
	this.shape_16.setTransform(-69,-15.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAcBMQgBAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhwIgxAAIAABwQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIgmAAQgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAiRQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAABAAICDAAQABAAAAAAQABAAAAABQABAAAAAAQAAABAAABIAACRQAAABAAABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_17.setTransform(-85.6,-15.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib._continue, new cjs.Rectangle(-99.7,-26.9,199.4,53.9), null);


(lib.fotootchet_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_31.setTransform(49.5,-1.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#ff9797").s().p("AgrA4IgBgBIgDgLQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAHgCQADAAADgDQADgCABgEIAEgJIABgKIABgMIABgMIAAgNIAAgcQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIBBAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAABpQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgMAAQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhdIglAAIAAATIgBAcIgCATIgFANQgDAHgFAEQgEADgFACIgKACIgCAAIAAAAg");
	this.shape_32.setTransform(36.9,-1.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#ff9797").s().p("AgfA3IgCAAIgBgCIAAhpIABgCIACAAIA/AAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgyAAIAAAhIApAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgpAAIAAAmIAyAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_33.setTransform(27.5,-1.4);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#ff9797").s().p("AgEA3IgDAAIAAgCIAAheIghAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAABAAIBSAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgiAAIAABeIgBACIgBAAg");
	this.shape_34.setTransform(17.8,-1.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_35.setTransform(7,-1.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#ff9797").s().p("AAtBFQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgZIhVAAIAAAZQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAIgCgBIAAgBIgCgkQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAIAJgRIAEgQQADgLABgNIABgZIAAgMQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIBAAAIACABIABACIAABeIANAAIACAAIABACIgCAkQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgLgqIgBAVIgDAUIgFAPQgDAIgDAHIA1AAIAAhTIgmAAg");
	this.shape_36.setTransform(-5.4,-0.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#ff9797").s().p("AggA3IgBAAIgBgCIAAhpIABgCIABAAIA/AAQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAIgwAAIAAAhIAoAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgoAAIAAAmIAxAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_37.setTransform(-15.6,-1.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#ff9797").s().p("AglA3IgCAAIgBgCIAAhpQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIBDAAIACAAIABACIAAAJQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIg1AAIAAAgIAYAAQAnAAAAAfQAAARgKAIQgKAIgSAAgAgXArIAYAAQALgBAGgFQAFgEAAgLQAAgKgFgFQgGgEgLAAIgYAAg");
	this.shape_38.setTransform(-25.8,-1.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#ff9797").s().p("AgVA2QgJgDgHgGQgGgHgEgLQgDgLAAgQQAAgbAMgPQAMgOAaAAQAaAAAMANQANAPAAAcQAAAQgEALQgDALgHAHQgHAGgJADQgKADgLAAQgLAAgKgDgAgPgoQgHADgEAFQgDAGgCAJQgCAHAAAKQAAAKACAIQACAJAEAGQADAFAHADQAGACAJABQAJgBAHgCQAGgDAEgFQAEgGACgIQABgIAAgKQAAgKgCgJQgBgIgEgGQgEgGgHgCQgGgDgJAAQgJAAgGADg");
	this.shape_39.setTransform(-37.6,-1.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#ff9797").s().p("AAdA3QAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAheIg1AAIAABeIAAACIgCAAIgMAAIgCAAIAAgCIAAhpIAAgCIACAAIBRAAIACAAIAAACIAABpQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_40.setTransform(-49.7,-1.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#ff9797").s().p("AogAFIAAgJIRBAAIAAAJg");
	this.shape_41.setTransform(0,6.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_42.setTransform(49.5,-1.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#ff9797").s().p("AgrA4IgBgBIgDgLQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIAHgCQADAAADgDQADgCABgEIAEgJIABgKIABgMIABgMIAAgNIAAgcQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIBBAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAABpQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgMAAQgBAAgBgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAhdIglAAIAAATIgBAcIgCATIgFANQgDAHgFAEQgEADgFACIgKACIgCAAIAAAAg");
	this.shape_43.setTransform(36.9,-1.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#ff9797").s().p("AgfA3IgCAAIgBgCIAAhpIABgCIACAAIA/AAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgyAAIAAAhIApAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgpAAIAAAmIAyAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_44.setTransform(27.5,-1.4);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#ff9797").s().p("AgEA3IgDAAIAAgCIAAheIghAAQgBAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgJQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAABAAIBSAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAIgiAAIAABeIgBACIgBAAg");
	this.shape_45.setTransform(17.8,-1.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#ff9797").s().p("AAfA3QAAAAgBAAQAAAAAAAAQAAAAgBgBQAAAAAAAAIAAhFIAAgLIABgJIgBAAIgEAJIgFAJIgsBHIgBABIgCAAIgPAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAhqIAAgCIACAAIAMAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAABBIAAAMIgBAKIABAAIAEgJIAGgJIAqhGQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIAQAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABqQAAAAAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAg");
	this.shape_46.setTransform(7,-1.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#ff9797").s().p("AAtBFQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgZIhVAAIAAAZQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgKAAIgCgBIAAgBIgCgkQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAABAAIALAAIAJgRIAEgQQADgLABgNIABgZIAAgMQAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIBAAAIACABIABACIAABeIANAAIACAAIABACIgCAkQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAgAgLgqIgBAVIgDAUIgFAPQgDAIgDAHIA1AAIAAhTIgmAAg");
	this.shape_47.setTransform(-5.4,-0.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#ff9797").s().p("AggA3IgBAAIgBgCIAAhpIABgCIABAAIA/AAQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAAAJQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAgBAAIgwAAIAAAhIAoAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAIQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgoAAIAAAmIAxAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAIQAAABAAAAQAAABgBAAQAAAAAAAAQgBAAgBAAg");
	this.shape_48.setTransform(-15.6,-1.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#ff9797").s().p("AglA3IgCAAIgBgCIAAhpQAAgBABAAQAAgBAAAAQAAAAABAAQAAAAABAAIBDAAIACAAIABACIAAAJQAAABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIg1AAIAAAgIAYAAQAnAAAAAfQAAARgKAIQgKAIgSAAgAgXArIAYAAQALgBAGgFQAFgEAAgLQAAgKgFgFQgGgEgLAAIgYAAg");
	this.shape_49.setTransform(-25.8,-1.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#ff9797").s().p("AgVA2QgJgDgHgGQgGgHgEgLQgDgLAAgQQAAgbAMgPQAMgOAaAAQAaAAAMANQANAPAAAcQAAAQgEALQgDALgHAHQgHAGgJADQgKADgLAAQgLAAgKgDgAgPgoQgHADgEAFQgDAGgCAJQgCAHAAAKQAAAKACAIQACAJAEAGQADAFAHADQAGACAJABQAJgBAHgCQAGgDAEgFQAEgGACgIQABgIAAgKQAAgKgCgJQgBgIgEgGQgEgGgHgCQgGgDgJAAQgJAAgGADg");
	this.shape_50.setTransform(-37.6,-1.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#ff9797").s().p("AAdA3QAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAheIg1AAIAABeIAAACIgCAAIgMAAIgCAAIAAgCIAAhpIAAgCIACAAIBRAAIACAAIAAACIAABpQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_51.setTransform(-49.7,-1.4);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#ff9797").s().p("AogAFIAAgJIRBAAIAAAJg");
	this.shape_52.setTransform(0,6.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#ff9797").s().p("Ao7BkIAAjHIR3AAIAADHg");
	this.shape_53.setTransform(0.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31}]}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42}]},1).to({state:[{t:this.shape_53}]},2).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.5,-10,195.1,20.1);


(lib.path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// rect1
	this.instance = new lib.rect1();
	this.instance.parent = this;
	this.instance.setTransform(-741,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:0},34).wait(16));

	// half_circle copy
	this.instance_1 = new lib.half_circle();
	this.instance_1.parent = this;
	this.instance_1.setTransform(740,117,1,1,180);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(34).to({_off:false},0).to({rotation:270},15).wait(1));

	// half_circle
	this.instance_2 = new lib.half_circle();
	this.instance_2.parent = this;
	this.instance_2.setTransform(740,117,1,1,180);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(34).to({_off:false},0).to({rotation:360},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-741,-15,741,30);


(lib.city4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.videoBtn.addEventListener('click', clickHandler);
		function clickHandler() {
			window.open('https://vk.com/videos-48512305?section=album_56048198', '_blank');
		}
		
		this.winners.addEventListener('click', clickHandler2);
		function clickHandler2() {
			window.open('https://vk.com/wall-48512305_1078275', '_blank');
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Тверь
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhRBhQgEAAAAgDIAAi7QAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIAwAAIACABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABAIArAAQAQAAANADQAOAEAJAIQAKAHAFALQAFAMAAAQQAAAUgGANQgHANgLAHQgKAHgNADQgNACgNAAgAgdA4IAnAAQAIgBAFgFQAFgEAAgNQAAgLgEgGQgDgGgKAAIgoAAg");
	this.shape.setTransform(148.8,-5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhQBhQgEAAAAgEIAAi5QAAgEAEAAIBgAAQAPAAAMADQANAEAJAIQAJAIAGALQAFAMAAARQAAAQgGANQgFAKgKAIQgLAJgNADQgOAFgPAAIgnAAIAAA+QAAAEgEAAgAgcgLIAmAAQAKAAAEgEQAEgGAAgMQAAgMgEgFQgEgEgJgBIgnAAg");
	this.shape_1.setTransform(129.1,-5.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhEBhQgFAAAAgEIAAi5QAAgEAFAAICKAAQAEAAAAAEIAAAlQAAADgFABIhVAAIAAAcIBBAAQAFAAAAADIAAAkQAAAEgFAAIhBAAIAAAgIBVAAQAEABAAADIAAAlQAAAEgEAAg");
	this.shape_2.setTransform(109.9,-5.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhQBhQgFAAABgEIAAi5QgBgEAFAAIBfAAQAiAAAQANQAQANAAAXQAAARgKALQgKAKgTAFIAAABQAsAIAAAmQgBAPgFALQgHAKgJAGQgKAHgMADQgNACgNAAgAgcA3IAnAAQAKAAAEgEQADgEAAgKQAAgLgDgDQgEgEgMgBIglAAgAgcgVIAmAAQAIAAADgDQADgEABgLQgBgJgDgDQgEgDgHgBIgmAAg");
	this.shape_3.setTransform(91.1,-5.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXBhQgFAAABgEIAAiMIg6AAQgDAAAAgEIAAgpQAAgEADAAICqAAQAEAAABAEIAAApQgBAEgEAAIg5AAIAACMQAAAEgEAAg");
	this.shape_4.setTransform(71.4,-5.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// description
	this.description = new cjs.Text("7 марта", "18px 'TNT Sans'", "#FFFFFF");
	this.description.name = "description";
	this.description.textAlign = "center";
	this.description.lineHeight = 20;
	this.description.lineWidth = 216;
	this.description.parent = this;
	this.description.setTransform(110.2,16);

	this.timeline.addTween(cjs.Tween.get(this.description).wait(1));

	// fotoBtn
	this.videoBtn = new lib.fotootchet();
	this.videoBtn.name = "videoBtn";
	this.videoBtn.parent = this;
	this.videoBtn.setTransform(111.6,54);
	new cjs.ButtonHelper(this.videoBtn, 0, 1, 2, false, new lib.fotootchet(), 3);

	this.timeline.addTween(cjs.Tween.get(this.videoBtn).wait(1));

	// fotoBtn
	this.winners = new lib.fotootchet_1();
	this.winners.name = "winners";
	this.winners.parent = this;
	this.winners.setTransform(110.2,54);
	this.winners.visible = false;
	new cjs.ButtonHelper(this.winners, 0, 1, 2, false, new lib.fotootchet_1(), 3);

	this.timeline.addTween(cjs.Tween.get(this.winners).wait(1));

}).prototype = getMCSymbolPrototype(lib.city4, new cjs.Rectangle(0,-20,220.3,84.1), null);


(lib.city3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.videoBtn.addEventListener('click', clickHandler);
		function clickHandler() {
			window.open('https://vk.com/videos-48512305?section=album_56048197', '_blank');
		}
		
		this.winners.addEventListener('click', clickHandler2);
		function clickHandler2() {
			window.open('https://vk.com/tnt?w=wall-48512305_1077005', '_blank');
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Рыбинск
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAgBhIgYg1IgHgMQgCgFgFgCQgEgCgFgBIgNgBIgHAAIAABLQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgxAAQgBAAgBAAQgBAAAAAAQAAgBgBgBQAAAAAAgBIAAi6QAAgBAAgBQABAAAAgBQAAAAABAAQABgBABAAIAxAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAABCIAIAAIALAAQAFAAAEgCQADgCADgDIAFgJIANgaQAEgJAFgHQAFgGAGgDQAGgEAJgBIAVgBIAGAAQABABABAEIADAlIgBAEQAAABgBAAQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgEACQgCADgDAGIgHAOQgDAHgFAGQgFAFgFADIAAABQAFADAGAEIAKAMQAGAGAEAIIAJAQIAVApQACAEgDABIg1AKIgBAAQgEAAgBgDg");
	this.shape.setTransform(177.9,14.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AASBlQgYABgTgGQgTgFgMgNQgMgNgGgTQgGgUAAgaQAAgYAGgUQAFgTAMgMQALgNASgGQATgGAYAAIATABIASABIAMACIAPAGQACAAAAAEIgKApIgCACIgCAAIgLgDIgKgCIgMgDQgJgBgKgBQgLABgFACQgHADgEAFQgEAGgBAKIgBAZQAAAPABALQACALAEAGQAEAHAHADQAGACAKAAIAQgBIAOgCIAEgBIAGgCIAGgBIAFgCQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABIAKApQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgEADIgIACIgIABIgJABIgQACIgQAAg");
	this.shape_1.setTransform(157.9,14.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAlBhQgEAAgBgEIAAhIIhAAAIAABIQABAEgFAAIgwAAQgEAAAAgEIAAi5QAAgEAEAAIAwAAQAFAAgBAEIAABEIBAAAIAAhEQABgEAEAAIAvAAQAFAAAAAEIAAC5QAAAEgFAAg");
	this.shape_2.setTransform(138,14.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAqBhQgEAAAAgDIAAhSIAAgSIABgTIgBAAIgHAQIgLAWIgsBRIgCACIgDABIg8AAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBIAAi7QAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAxAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAABJIAAAMIgBALIAAALIAAAIIABAAIAFgLIAFgJIAFgJIAEgKIAphMIACgCIAEgBIA8AAQAEAAAAADIAAC7QAAABAAABQAAAAgBAAQAAABgBAAQgBAAgBAAg");
	this.shape_3.setTransform(115.9,14.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhOBhIgDgBIgBgCIAAi6QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBICQAAQAFAAAAADIAAApQAAAAAAAAQAAABgBAAQAAAAAAAAQAAABgBAAIgDABIhcAAIAAAcIAnAAQAPAAAMAEQANACAKAHQAJAHAGAKQAFALAAARQAAASgHAMQgGAMgLAHQgKAGgNADQgNACgNAAgAgaA3IAhAAIAHgBQADgBADgCQACgCACgDIABgJQAAgMgFgDQgFgDgHAAIgiAAg");
	this.shape_4.setTransform(95.3,14.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABGBhQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAi7QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAyAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAAC7IAAACIgDABgAh2BhQgFAAABgDIAAi7QAAAAAAAAQAAgBAAAAQAAAAAAgBQABAAAAAAIACgBIAxAAIACABQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAABAIArAAQAPAAANAEQANADAKAIQAKAGAFALQAGAMAAARQAAAUgHANQgHAMgKAIQgLAHgNACQgMADgMAAgAhCA4IAnAAQAJAAAFgGQAFgEAAgNQAAgNgFgFQgFgFgJAAIgnAAg");
	this.shape_5.setTransform(70.5,14.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhQBhQgEAAAAgEIAAi5QAAgEAEAAIBgAAQAPAAAMADQANAEAJAIQAJAIAGAMQAFALAAARQAAARgGALQgFAMgKAHQgLAJgNAEQgOADgPAAIgnAAIAAA/QAAAEgEAAgAgcgLIAmAAQAKAAAEgEQAEgGAAgMQAAgMgEgFQgEgFgJAAIgnAAg");
	this.shape_6.setTransform(47,14.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// description
	this.description = new cjs.Text("6 марта", "18px 'TNT Sans'", "#FFFFFF");
	this.description.name = "description";
	this.description.textAlign = "center";
	this.description.lineHeight = 20;
	this.description.lineWidth = 216;
	this.description.parent = this;
	this.description.setTransform(110.2,36);

	this.timeline.addTween(cjs.Tween.get(this.description).wait(1));

	// fotoBtn
	this.videoBtn = new lib.fotootchet();
	this.videoBtn.name = "videoBtn";
	this.videoBtn.parent = this;
	this.videoBtn.setTransform(111.6,72);
	new cjs.ButtonHelper(this.videoBtn, 0, 1, 2, false, new lib.fotootchet(), 3);

	this.timeline.addTween(cjs.Tween.get(this.videoBtn).wait(1));

	// fotoBtn
	this.winners = new lib.fotootchet_1();
	this.winners.name = "winners";
	this.winners.parent = this;
	this.winners.setTransform(111.6,74.8);
	this.winners.visible = false;
	new cjs.ButtonHelper(this.winners, 0, 1, 2, false, new lib.fotootchet_1(), 3);

	this.timeline.addTween(cjs.Tween.get(this.winners).wait(1));

}).prototype = getMCSymbolPrototype(lib.city3, new cjs.Rectangle(0,0,220.3,84.8), null);


(lib.city2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.videoBtn.addEventListener('click', clickHandler);
		function clickHandler() {
			window.open('https://vk.com/videos-48512305?section=album_56048196', '_blank');
		}
		
		this.winners.addEventListener('click', clickHandler2);
		function clickHandler2() {
			window.open('https://vk.com/tnt?w=wall-48512305_1075132', '_blank');
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Ярославль
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhRBhQgEAAAAgDIAAi7QAAAAAAAAQAAgBAAAAQAAAAABgBQAAAAAAAAIADgBIAwAAIACABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAABAIArAAQAQAAANAEQAOADAJAIQAKAIAFAKQAFAMAAAQQAAAVgGAMQgHAMgLAIQgKAHgNACQgNADgNAAgAgdA4IAnAAQAIAAAFgGQAFgEAAgNQAAgKgEgHQgDgGgKAAIgoAAg");
	this.shape.setTransform(193.9,14.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhRBjIgCgCIgLgnQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIAQgFQAHgCAFgGQAGgHACgPIACgUIABgZIAAhEQAAgEAEAAICMAAQAEAAAAAEIAAC5QAAAEgEAAIgwAAQgEAAAAgEIAAiPIgpAAIAAASIAAAdQgBAQgCAPIgDAPIgEAPQgCAHgEAGQgDAHgFAFQgLAKgOAEQgNAEgMAAIgFAAg");
	this.shape_1.setTransform(171.8,14.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhQBhQgEAAgBgEIAAi5QABgEAEAAIBfAAQAiAAAQANQAQANAAAXQAAARgKALQgKALgTADIAAABQArAJAAAmQABAQgHAJQgFALgKAGQgKAGgMADQgNADgNAAgAgdA3IAoAAQAKAAADgEQAFgEAAgKQAAgLgFgEQgEgDgKAAIgnAAgAgdgVIAoAAQAGAAAEgDQAEgEgBgLQABgJgEgDQgDgEgIAAIgnAAg");
	this.shape_2.setTransform(152.6,14.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhjBcQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBAAAAIAAgDIBBi1QABgEAEAAIBBAAQAEAAABAEIBBC0QACAEgFABIgyAHQgEAAgBgEIgMglIhCAAIgMAmQgBAEgEAAgAgDgpIgFAQIgNApIAqAAIgNgpIgEgRIgDgRIgBAAIgDASg");
	this.shape_3.setTransform(131.8,14.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhRBjIgCgCIgLgnQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIAQgFQAHgCAFgGQAGgHACgPIACgUIABgZIAAhEQAAgEAEAAICMAAQAEAAAAAEIAAC5QAAAEgEAAIgwAAQgEAAAAgEIAAiPIgpAAIAAASIAAAdQgBAQgCAPIgDAPIgEAPQgCAHgEAGQgDAHgFAFQgLAKgOAEQgNAEgMAAIgFAAg");
	this.shape_4.setTransform(110.1,14.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASBlQgYABgTgGQgTgFgMgNQgMgNgGgTQgGgUAAgaQAAgYAGgUQAFgTAMgMQALgNASgGQATgGAYAAIATABIASABIAMACIAPAGQACAAAAAEIgKApIgCACIgCAAIgLgDIgKgCIgMgDQgJgBgKgBQgLABgFACQgHADgEAFQgEAGgBAKIgBAZQAAAPABALQACALAEAGQAEAHAHADQAGACAKAAIAQgBIAOgCIAEgBIAGgCIAGgBIAFgCQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABIAKApQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgEADIgIACIgIABIgJABIgQACIgQAAg");
	this.shape_5.setTransform(91.6,14.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgrBgQgTgFgMgNQgLgNgGgUQgGgTAAgbQAAgYAFgTQAGgSALgNQANgNASgGQATgGAaAAQAZgBASAGQASAFAMAMQANAMAGATQAFATAAAbQAAAbgFATQgGAUgNANQgMANgSAFQgSAGgagBQgYABgTgGgAgRg0QgHADgFAFQgEAGgBALQgBALAAAQQAAASABALQABALAEAGQAFAGAHABQAHACALAAQAKAAAIgCQAHgBAEgHQAEgFACgMQABgLAAgRQAAgSgBgKQgCgKgEgGQgEgGgHgCQgIgBgKgBQgLAAgHACg");
	this.shape_6.setTransform(71.8,14.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhQBhQgEAAAAgEIAAi5QAAgEAEAAIBgAAQAPAAAMADQANAEAJAIQAJAIAGAMQAFALAAARQAAARgGALQgFAMgKAHQgLAJgNAEQgOADgPAAIgnAAIAAA/QAAAEgEAAgAgcgLIAmAAQAKAAAEgEQAEgGAAgMQAAgMgEgFQgEgFgJAAIgnAAg");
	this.shape_7.setTransform(51.8,14.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgoBjIgygLQgEgBACgFIAXgnIAGgLIAIgJIAIgJQAEgDAEgCIAAgBQgRgEgLgLQgMgMAAgSQAAgSAHgMQAHgMAKgHQALgHAMgDQANgCAMAAIBgAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABAAAAIABADIAAC6QAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIgxAAQgDAAAAgEIAAhAIgNAAQgGAAgFABQgFABgFAEQgDADgEAGIgJAOIgUAoQgCADgDAAIgCAAgAgPg1QgFAFAAAMQAAAOAFAEQAFAFAGAAIApAAIAAgsIgpAAQgGAAgFAEg");
	this.shape_8.setTransform(30.1,14.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// 11 и 12 сентября Соборная Площадь
	this.description = new cjs.Text("5 марта", "18px 'TNT Sans'", "#FFFFFF");
	this.description.name = "description";
	this.description.textAlign = "center";
	this.description.lineHeight = 20;
	this.description.lineWidth = 216;
	this.description.parent = this;
	this.description.setTransform(110.2,36);

	this.timeline.addTween(cjs.Tween.get(this.description).wait(1));

	// fotoBtn
	this.videoBtn = new lib.fotootchet();
	this.videoBtn.name = "videoBtn";
	this.videoBtn.parent = this;
	this.videoBtn.setTransform(111.6,72);
	new cjs.ButtonHelper(this.videoBtn, 0, 1, 2, false, new lib.fotootchet(), 3);

	this.timeline.addTween(cjs.Tween.get(this.videoBtn).wait(1));

	// fotootchet
	this.winners = new lib.fotootchet_1();
	this.winners.name = "winners";
	this.winners.parent = this;
	this.winners.setTransform(111.6,73.4);
	this.winners.visible = false;
	new cjs.ButtonHelper(this.winners, 0, 1, 2, false, new lib.fotootchet_1(), 3);

	this.timeline.addTween(cjs.Tween.get(this.winners).wait(1));

}).prototype = getMCSymbolPrototype(lib.city2, new cjs.Rectangle(0,0,220.3,83.4), null);


(lib.city1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.videoBtn.addEventListener('click', clickHandler);
		function clickHandler() {
			window.open('https://vk.com/videos-48512305?section=album_56048195', '_blank');
		}
		
		this.winners.addEventListener('click', clickHandler2);
		function clickHandler2() {
			window.open('https://vk.com/wall-48512305_1079638', '_blank');
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// МОСКВА
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhjBcQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBAAAAIAAgDIBBi1QABgEAEAAIBBAAQAEAAABAEIBBC0QACAEgFABIgyAHQgEAAgBgEIgMglIhCAAIgMAmQgBAEgEAAgAgDgpIgFAQIgNApIAqAAIgNgpIgEgRIgDgRIgBAAIgDASg");
	this.shape.setTransform(144.4,14.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhQBhQgFAAAAgEIAAi5QAAgEAFAAIBfAAQAiAAAQANQAQANAAAXQAAARgKALQgKALgTADIAAABQArAJAAAmQAAAQgFAJQgHALgJAGQgKAGgMADQgMADgNAAgAgcA3IAnAAQAKAAAEgEQADgEAAgKQAAgLgDgEQgFgDgKAAIgmAAgAgcgVIAmAAQAIAAADgDQAEgEAAgLQAAgJgEgDQgDgEgIAAIgmAAg");
	this.shape_1.setTransform(124.6,14.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAgBhIgYg1IgHgMQgCgFgFgCQgEgCgFgBIgNgBIgHAAIAABLQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAgBAAIgxAAQgBAAgBAAQgBAAAAAAQAAgBgBgBQAAAAAAgBIAAi6QAAgBAAgBQABAAAAgBQAAAAABAAQABgBABAAIAxAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAABCIAIAAIALAAQAFAAAEgCQADgCADgDIAFgJIANgaQAEgJAFgHQAFgGAGgDQAGgEAJgBIAVgBIAGAAQABABABAEIADAlIgBAEQAAABgBAAQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgEACQgCADgDAGIgHAOQgDAHgFAGQgFAFgFADIAAABQAFADAGAEIAKAMQAGAGAEAIIAJAQIAVApQACAEgDABIg1AKIgBAAQgEAAgBgDg");
	this.shape_2.setTransform(104.8,14.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AASBlQgYABgTgGQgTgFgMgNQgMgNgGgTQgGgUAAgaQAAgYAGgUQAFgTAMgMQALgNASgGQATgGAYAAIATABIASABIAMACIAPAGQACAAAAAEIgKApIgCACIgCAAIgLgDIgKgCIgMgDQgJgBgKgBQgLABgFACQgHADgEAFQgEAGgBAKIgBAZQAAAPABALQACALAEAGQAEAHAHADQAGACAKAAIAQgBIAOgCIAEgBIAGgCIAGgBIAFgCQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABIAKApQAAABAAABQAAAAAAABQAAAAgBABQAAAAgBAAIgEADIgIACIgIABIgJABIgQACIgQAAg");
	this.shape_3.setTransform(84.9,14.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgrBgQgTgFgMgNQgLgNgGgUQgGgTAAgbQAAgYAFgTQAGgSALgNQANgNASgGQATgGAaAAQAZgBASAGQASAFAMAMQANAMAGATQAFATAAAbQAAAbgFATQgGAUgNANQgMANgSAFQgSAGgagBQgYABgTgGgAgRg0QgHADgFAFQgEAGgBALQgBALAAAQQAAASABALQABALAEAGQAFAGAHABQAHACALAAQAKAAAIgCQAHgBAEgHQAEgFACgMQABgLAAgRQAAgSgBgKQgCgKgEgGQgEgGgHgCQgIgBgKgBQgLAAgHACg");
	this.shape_4.setTransform(65,14.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("ABBBeIgDhbIAAgJIABgLIAAgMIABgLIgBAAIgLAoIgTBFQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAIgEABIg1AAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIgUhGIgFgSIgFgWIgBAAIABAXIAAAUIgCBbQAAAEgDAAIgxgCQgEAAAAgDIAIi6QAAgEAEAAIBIAAIAFABIABAEIAWBLIAFARIADASIACAAIAEgSIAEgRIAWhKQABgEABgBIAFgBIBFAAQAFAAAAAEIAIC6QAAADgEAAIgwACQgEAAAAgEg");
	this.shape_5.setTransform(40.4,14.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// 9 и 10 сентября Парк Горького
	this.description = new cjs.Text("8 марта", "18px 'TNT Sans'", "#FFFFFF");
	this.description.name = "description";
	this.description.textAlign = "center";
	this.description.lineHeight = 20;
	this.description.lineWidth = 231;
	this.description.parent = this;
	this.description.setTransform(90.7,36);

	this.timeline.addTween(cjs.Tween.get(this.description).wait(1));

	// fotoBtn
	this.videoBtn = new lib.fotootchet();
	this.videoBtn.name = "videoBtn";
	this.videoBtn.parent = this;
	this.videoBtn.setTransform(90.7,72);
	new cjs.ButtonHelper(this.videoBtn, 0, 1, 2, false, new lib.fotootchet(), 3);

	this.timeline.addTween(cjs.Tween.get(this.videoBtn).wait(1));

	// fotootchet
	this.winners = new lib.fotootchet_1();
	this.winners.name = "winners";
	this.winners.parent = this;
	this.winners.setTransform(88.7,73.4);
	this.winners.visible = false;
	new cjs.ButtonHelper(this.winners, 0, 1, 2, false, new lib.fotootchet_1(), 3);

	this.timeline.addTween(cjs.Tween.get(this.winners).wait(1));

}).prototype = getMCSymbolPrototype(lib.city1, new cjs.Rectangle(-27,0,235.3,83.4), null);


(lib.City = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_10 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(10).call(this.frame_10).wait(1));

	// Layer 1
	this.instance = new lib.point();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.27,scaleY:0.27,alpha:1},0).to({scaleX:1,scaleY:1},9,cjs.Ease.quadOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30,-30,60,60);


(lib.Road = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var currentCity;// = this.city11;
		var notHash = false;
		
		this.stop();
		this.start = function(id) {	
			if (id < 0) {
				notHash = true;
				id = -id;
			}
			currentCity = this['city' + id];
			this.play();
		}
		
		this.showCity = function(city, p) {
			var time = 300;
			cjs.Tween.get(city).to({alpha:1}, time);
			if (currentCity == city) {
				this.stop();
				city.videoBtn.visible = !notHash;
				city.winners.visible = notHash;
			} else {
				city.videoBtn.visible = false;
				city.winners.visible = true;
			}
		}
	}
	this.frame_1 = function() {
		this.showCity(this.city1, this.p1);
	}
	this.frame_20 = function() {
		this.showCity(this.city2, this.p2);
	}
	this.frame_54 = function() {
		this.showCity(this.city3, this.p3);
	}
	this.frame_71 = function() {
		this.showCity(this.city4, this.p4);
	}
	this.frame_120 = function() {
		cjs.Tween.get(this.finish).to({alpha:1}, 300);
		cjs.Tween.get(this.contin).to({alpha:1}, 300);
	}
	this.frame_128 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(19).call(this.frame_20).wait(34).call(this.frame_54).wait(17).call(this.frame_71).wait(49).call(this.frame_120).wait(8).call(this.frame_128).wait(1));

	// citys
	this.city3 = new lib.city4();
	this.city3.name = "city3";
	this.city3.parent = this;
	this.city3.setTransform(733.9,189.8,1,1,0,0,0,110.2,51.7);
	this.city3.alpha = 0.602;

	this.city2 = new lib.city3();
	this.city2.name = "city2";
	this.city2.parent = this;
	this.city2.setTransform(547,-68.2,1,1,0,0,0,110.2,51.7);
	this.city2.alpha = 0.602;

	this.city1 = new lib.city2();
	this.city1.name = "city1";
	this.city1.parent = this;
	this.city1.setTransform(178.2,-68.2,1,1,0,0,0,110.2,51.7);
	this.city1.alpha = 0.602;

	this.city4 = new lib.city1();
	this.city4.name = "city4";
	this.city4.parent = this;
	this.city4.setTransform(357.7,170.8,1,1,0,0,0,88.5,51.7);
	this.city4.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.city4},{t:this.city1},{t:this.city2},{t:this.city3}]}).wait(129));

	// city4
	this.p4 = new lib.City();
	this.p4.name = "p4";
	this.p4.parent = this;
	this.p4.setTransform(358,237);
	this.p4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.p4).wait(71).to({_off:false},0).wait(58));

	// city3
	this.p3 = new lib.City();
	this.p3.name = "p3";
	this.p3.parent = this;
	this.p3.setTransform(734,237);
	this.p3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.p3).wait(53).to({_off:false},0).wait(76));

	// city2
	this.p2 = new lib.City();
	this.p2.name = "p2";
	this.p2.parent = this;
	this.p2.setTransform(547,-2);
	this.p2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.p2).wait(19).to({_off:false},0).wait(110));

	// city1
	this.p1 = new lib.City();
	this.p1.name = "p1";
	this.p1.parent = this;
	this.p1.setTransform(178,-2);
	this.p1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.p1).wait(1).to({_off:false},0).wait(128));

	// Layer 1 copy (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Eg51AlgQm3AAk2k2Qk3k3AAm3IAAlUQAAm3E3k3QE2k1G3AAMBzrAAAQGFAAETkUQEUkSAAmGIAAlUQAAmFkUkUQkTkTmFAAMhjNAAAIAAh4MBjNAAAQG3AAE2E2QE3E3AAG3IAAFUQAAG3k3E3Qk2E1m3AAMhzrAAAQmFAAkTETQkUEUAAGFIAAFUQAAGGEUESQETEUGFAAMBjnAAAQAZAAASASQARARAAAZQAAAZgRARQgSASgZAAg");
	mask.setTransform(470.2,234);

	// Layer 1
	this.instance = new lib.path("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(109.8,0);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(129));

	// Layer 1 copy 2
	this.instance_1 = new lib.path("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(850,233,1,1,0,0,180);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(49).to({_off:false},0).wait(80));

	// Layer 1 copy 3
	this.instance_2 = new lib.path("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(109.8,468);
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(97).to({_off:false},0).wait(32));

	// points
	this.instance_3 = new lib.point2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(178,-2);
	

	this.contin = new lib._continue();
	this.contin.name = "contin";
	this.contin.parent = this;
	this.contin.setTransform(842,466);
	this.contin.alpha = 0.602;

	this.finish = new lib.flags_1();
	this.finish.name = "finish";
	this.finish.parent = this;
	this.finish.setTransform(550.3,373.6);
	this.finish.alpha = 0.602;

	this.instance_4 = new lib.point2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(358,237);


	this.instance_5 = new lib.point2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(734,237);


	this.instance_6 = new lib.point2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(547,-2);


	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.finish},{t:this.contin},{t:this.instance_3}]}).wait(129));

	// road
	this.instance_7 = new lib.mask();
	this.instance_7.parent = this;
	this.instance_7.setTransform(470.2,819,1,1,0,0,0,476.2,825);
	this.instance_7.alpha = 1;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(129));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-6,-119.9,952.4,612.9);


// stage content:
(lib.snake_mini = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var road = this.road;
		var xhr = new XMLHttpRequest();
		xhr.open('GET', 'http://tnt-design.tnt-online.ru/date.php?anticache=' + Math.random(), true);
		xhr.onload = timeLoadCompleteHandler;
		xhr.send();
		
		var startData = new Date(2018, 2, 5);
		var endData = new Date(2018, 2, 8);
		
		var totalDays = (endData - startData) / (1000 * 60 * 60 * 24);
		var citys = [1,2,3,4];
		
		function timeLoadCompleteHandler(e) {			
				road.start(5);					
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Layer_1
	this.road = new lib.Road();
	this.road.name = "road";
	this.road.parent = this;
	this.road.setTransform(477.6,1027,1,1,0,0,0,470.2,819);

	this.timeline.addTween(cjs.Tween.get(this.road).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-145.8,375,1581.1,759.4);
// library properties:
lib.properties = {
	id: 'AE001D10AD71E04BB04869299E178ABD',
	width: 956,
	height: 750,
	fps: 30,
	color: "#000000",
	opacity: 0.00,
	manifest: [
		{src:"images/flags.png", id:"flags"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['AE001D10AD71E04BB04869299E178ABD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;